application: udec
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /rest/.*
  script: services.app

- url: /bower_components
  static_dir: bower_components

- url: (.*)/
  static_files: app\1/index.html
  upload: app

- url: (.*)
  static_files: app\1
  upload: app

libraries:
  - name: webapp2
    version: latest